---
env:
  name: PathFollower-v0
  max_episode_steps: 2000
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    mode: abs
    epi_steps: 2000
  info: oha
agent:
  DQN: {}
  DDQN: {}
  SCDQN_a:
    sc_beta: 2
  SCDQN_b:
    sc_beta: 3
  SCDQN_c:
    sc_beta: 4
  ACCDDQN_a:
    AC_K: 2
  BootDQN:
    K: 10
    mask_p: 1
    grad_rescale: true
  EnsembleDQN:
    N: 5
    N_to_update: 1
  MaxMinDQN_a:
    N: 2
    N_to_update: 1
  MaxMinDQN_b:
    N: 5
    N_to_update: 1
  ComboDQN: {}
img_height: 120
img_width: 120
seed: 26757
timesteps: 10_000_000
epoch_length: 5000
eval_episodes: 10
dqn_weights:
input_norm: false
input_norm_prior:
gamma: 0.99
eps_init: 1
eps_final: 0.1
eps_decay_steps: 2_000_000
tgt_update_freq: 1000
net_struc:
  - - 256
    - relu
  - - 128
    - relu
  - identity
optimizer: Adam
loss: MSELoss
lr: 0.001
buffer_length: 500_000
grad_rescale: false
mode: train
grad_clip: false
act_start_step: 1000
upd_start_step: 1000
upd_every: 1
batch_size: 128
device: cuda
output_dir:
